# -*- coding: utf-8 -*-
"""
Set certain configs for calculation of face embeddings
and clustering
"""

ENVIRON = {
   'test': dict(
            FACE_CONFIDENCE = 0.9,
            EVERY_NTH_FRAME = 5,
            CROP_FRAMES = {'top': 300, 'bottom': 1100,
                           'left': 0, 'right': 2400},
            MIN_SPATIAL = 55,
            RESIZE_FRAMES = None,
            BEGIN_FRAME = None,
            MAX_FRAMES = 2500,
            BATCH_SIZE = 16,
            DETECTOR = 'mtcnn',
            RECOGNITION = 'facenet',
            NAME='retrieve',
            FILE_DEPTH = 2,
            VIDEO_PATH = '/mnt/neurus_storage04/RG_mnt/juul_{date}/',
#            VIDEO_PATH = '/mnt/neurus_storage04/RG_mnt/juul_{date}/1563519601.mp4',
            DETECTED_FACES = 'data/interim/{name}_{detector}/',
            TMP_DIR = 'data/tmp',
            WRITE_DETECTIONS = 'data/interim/embeddings/{name}_{detector}.hdf5',
            WRITE_EMBEDDINGS = 'data/interim/embeddings/{name}_{recognition}.hdf5',
            WRITE_CLUSTERS = 'data/interim/clusters/{name}.npy',
            WRITE_SILHOUETTE = 'data/interim/clusters/{name}_silhouette.csv',
            WRITE_RESULTS = 'data/processed/clusters/{name}_{date}.csv',
            WRITE_DEMOGRAPHICS = 'data/processed/clusters/{name}_{date}_demographics.pkl',
            WRITE_FRAMES = 'data/processed/juul_photos/{name}_{date}/',
            VIDEO_EXTENSIONS = ['mp4'],
            RECOGNITION_MODEL_PATH = {
                    'facenet': 'models/20180402-114759/20180402-114759.pb',
                    'dlib': '/home/neuro/dlib/dlib_face_recognition_resnet_model_v1.dat',
                    },
            SHAPE_PREDICTOR_PATH = '/home/neuro/dlib/shape_predictor_5_face_landmarks.dat',
            DETECTOR_WEIGHTS = {
                        'mobilenet_ssd': 'models/external/frozen_inference_graph_face.pb',
                        'mtcnn': 'src/FaceDetector/output/caffe_models/',
                        'dlib': '/home/neuro/dlib/mmod_human_face_detector.dat',
                        },
            DB_CONNECTION = dict(
                            dbname='juuldb',
                            user='neurus',
                            password='B4QjFsAL',
                            host='172.17.0.2',
                            port='5432',
                            )
        ),
   'docker': dict(
            FACE_CONFIDENCE = 0.9,
            EVERY_NTH_FRAME = 5,
            CROP_FRAMES = {'top': 300, 'bottom': 1100,
                           'left': 0, 'right': 2400},
            MIN_SPATIAL = 55,
            RESIZE_FRAMES = None,
            BEGIN_FRAME = None,
            MAX_FRAMES = None,
            BATCH_SIZE = 16,
            DETECTOR = 'mtcnn',
            RECOGNITION = 'facenet',
            NAME='docker',
            FILE_DEPTH = 2,
            VIDEO_PATH = '/mnt/neurus_storage04/RG_mnt/juul_{date}/',
            DETECTED_FACES = 'data/interim/{name}_{detector}/',
            TMP_DIR = 'data/tmp',
            WRITE_DETECTIONS = 'data/interim/embeddings/{name}_{detector}.hdf5',
            WRITE_EMBEDDINGS = 'data/interim/embeddings/{name}_{recognition}.hdf5',
            WRITE_CLUSTERS = 'data/interim/clusters/{name}.npy',
            WRITE_SILHOUETTE = '/mnt/neurus_storage04/RG_mnt/juul_results/{name}_silhouette.csv',
            WRITE_RESULTS = '/mnt/neurus_storage04/RG_mnt/juul_results/{name}_{date}.csv',
            WRITE_DEMOGRAPHICS = '/mnt/neurus_storage04/RG_mnt/juul_results/{name}_{date}_demographics.pkl',
            WRITE_FRAMES = '/mnt/neurus_storage04/RG_mnt/juul_photos_{date}/',
            VIDEO_EXTENSIONS = ['mp4'],
            RECOGNITION_MODEL_PATH = {
                    'facenet': 'models/20180402-114759/20180402-114759.pb',
                    'dlib': '/home/neuro/dlib/dlib_face_recognition_resnet_model_v1.dat',
                    },
            SHAPE_PREDICTOR_PATH = '/root/people_count/dlib/shape_predictor_5_face_landmarks.dat',
            DETECTOR_WEIGHTS = {
                        'mobilenet_ssd': 'models/external/frozen_inference_graph_face.pb',
                        'mtcnn': 'src/FaceDetector/output/caffe_models/',
                        'dlib': '/root/people_count/dlib/mmod_human_face_detector.dat',
                        },
            DB_CONNECTION = dict(
                            dbname='juuldb',
                            user='neurus',
                            password='B4QjFsAL',
                            host='172.17.0.2',
                            port='5432',
                            )
        ),
    'juul': dict(
        FACE_CONFIDENCE = 0.9,
        EVERY_NTH_FRAME = 5,
        CROP_FRAMES = {'top': 300, 'bottom': 1100,
                       'left': 0, 'right': 2400},
        MIN_SPATIAL = 55,
        RESIZE_FRAMES = None,
        BEGIN_FRAME = None,
        MAX_FRAMES = None,
        BATCH_SIZE = 16,
        DETECTOR = 'mtcnn',
        RECOGNITION = 'facenet',
        NAME='juul',
        FILE_DEPTH = 2,
        VIDEO_PATH = '/mnt/neurus_storage05/juul/{date}/',
        DETECTED_FACES = 'data/interim/{name}_{detector}/',
        TMP_DIR = 'data/tmp',
        WRITE_DETECTIONS = 'data/interim/embeddings/{name}_{detector}.hdf5',
        WRITE_EMBEDDINGS = 'data/interim/embeddings/{name}_{recognition}.hdf5',
        WRITE_CLUSTERS = 'data/interim/clusters/{name}.npy',
        WRITE_SILHOUETTE = '/mnt/neurus_storage05/juul/results/{name}_silhouette.csv',
        WRITE_RESULTS = '/mnt/neurus_storage05/juul/results/{name}_{date}.csv',
        WRITE_DEMOGRAPHICS = 'data/interim/clusters/{name}_demographics.pkl',
        WRITE_FRAMES = '/mnt/neurus_storage05/juul/results/juul_photos_{date}/',
        VIDEO_EXTENSIONS = ['mp4'],
        RECOGNITION_MODEL_PATH = {
                'facenet': 'models/20180402-114759/20180402-114759.pb',
                'dlib': '/home/neuro/dlib/dlib_face_recognition_resnet_model_v1.dat',
                },
        SHAPE_PREDICTOR_PATH = '/root/people_count/dlib/shape_predictor_5_face_landmarks.dat',
        DETECTOR_WEIGHTS = {
                    'mobilenet_ssd': 'models/external/frozen_inference_graph_face.pb',
                    'mtcnn': 'src/FaceDetector/output/caffe_models/',
                    'dlib': '/root/people_count/dlib/mmod_human_face_detector.dat',
                    },
        DB_CONNECTION = dict(
                        dbname='juuldb',
                        user='neurus',
                        password='B4QjFsAL',
                        host='10.1.253.148',
                        port='5432',
                        )
        ),
       }
